### PR TITLE
Adapting to changes in Pulseaudio packaging

### PR DESCRIPTION
**Pull request by peat-psuwit**
pulseaudio-modules-droid uses version macro to guard the _choose_initial
_profile call for PA version 10 or later. However, the patch that
requires this has been backported in version 1:8.0-1ubports6~exp1. So,
the guard has to be removed.

To make sure that it will build, the build-depends has been made to
require this newer version or version 10.

This PR also brings back SCO fake sink for the new pulseaudio-module-droid, as it's required by the new pulseaudio.

This depends on ubports/pulseaudio-packaging#3.

### CODE REVIEW

**Review by UniversalSuperBox — APPROVED** [review]
Approving with https://github.com/ubports/pulseaudio-packaging/pull/3#pullrequestreview-441167049

**Comment by jezek** [comment]
There is a call for testing. How do we test this, please?

**Comment by peat-psuwit** [comment]
With a device with Android 5 base (FP2, OPO, Nexus 5), please follow the test plan here:
https://wiki.ubuntu.com/Process/Merges/TestPlan/pulseaudio

**Comment by jezek** [comment]
> With a device with Android 5 base (FP2, OPO, Nexus 5), please follow the test plan here:
> https://wiki.ubuntu.com/Process/Merges/TestPlan/pulseaudio

Device: FP2
Image: 2020-W37

* Check that there's a default card provided by the droid module :heavy_check_mark: 
* Import audio/video files into your phone, and try playing them using the music-app/mediaplayer-app :heavy_check_mark:
* Testing basic audio recording with parecord and paplay :heavy_check_mark:
* Check that the sink-input used by media-hub when playing via music-app/mediaplayer-app has the multimedia media role :heavy_check_mark:
* Check that the sink-input used by media-hub when playing ringtone/notification has the alert media role :heavy_check_mark:
* Check that the sink-input used by media-hub when playing alarm has the alarm media role :heavy_check_mark:
* Check that there is sink-input using the phone media role when a call is active :heavy_check_mark: 
* Play an audio using the music-app and start a call. The audio from the music-app should be corked while the phone call is active :heavy_check_mark: 
* Play an audio/video using the webbrowser and trigger an alarm. The audio from the webbrowser should be corked while the alarm call is active. :heavy_check_mark:
* Play an audio/video using the webbrowser and trigger a ringtone/notification. The audio from the webbrowser should be reduced (ducking effect) while the ringtone/notification is active. :heavy_check_mark:
* Play a song with music-app and connect a bluetooth device (with A2DP). The audio from music-app should automatically move to the bluetooth device. :negative_squared_cross_mark: It works the first time, the second time it doesn't. I can see the notification but does not route the audio to the handset. I have to restart music app to play from BT device.
* While playing a song with a bluetooth device connected, turn the bluetooth device off. The audio from music-app should automatically move to the internal speaker. :thinking: The audio is paused. In my opinion it's fine like that.


thanks to template to @Bolly in https://github.com/ubports/pulseaudio-packaging/pull/3#issuecomment-688785559_

**Pull request merged**
