### PR TITLE
Compile for multiple Android versions at the same time

### PR DESCRIPTION
**Pull request by peat-psuwit**
This PR makes our pulseaudio-module-droid package builds with multiple Android APIs at the same time. This prevents hardcoding any specific version into the source code, and allow building this code for older Android versions in the future when we decided to upgrade Pulseaudio.

### CODE REVIEW

**Comment by dobey** [comment]
Is this still relevant? We have a different branch for the android9 stuff now right? We don't use this `xenial_-_edge_-_android8` anymore?

**Comment by mariogrip** [comment]
I would still like to get this in, now that we got both android9 and 10 this is needed

**Comment by peat-psuwit** [comment]
Should I rebase this on `xenial_-_android9` or `xenial_-_android9_-_android10`? They're disjoint from each other.

**Comment by mariogrip** [comment]
@peat-psuwit yes please

**Comment by peat-psuwit** [comment]
I didn't expect a confirmation from the above question. 😆

I mean, which branch are you going to merge in? Maybe @NotKit knows better.

**Comment by mariogrip** [comment]
Lol i didn't read your question, but xenial_-_android9
Is the correct target.

Apr 12, 2021 14:10:21 Ratchanan Srirattanamet ***@***.***>:

**Comment by peat-psuwit** [comment]
Because the branch name changes, superseded by #14.

**Pull request closed without merging**
