### PR TITLE
sink: move fake SCO property setting to a hook instead

### PR DESCRIPTION
**Pull request by peat-psuwit**
Pulseaudio calls the sink's set_port callback on IO thread instead of
main thread if "deferred volumes" are in use, and with 65483884 ("sink:
Enable deferred volume for hw volume control"), we're doing just that.
This means we cannot update SCO fake sink's property from that callback,
as an assert will cause the whole PA to crash.

Thus, move the property setting logic into a hook, which is guaranteed
to run on the main thread. Yes, I know that it's a little bit silly to
run hook for our own sink, but that's the way it has to be.

Note that we register a separated hook from the existing `sink_port_
changed_hook_cb`, since that one is used for another purpose and has
some hook/unhook logic which I would rather not touch.

Fixes: https://github.com/ubports/ubuntu-touch/issues/1977

### CODE REVIEW

**Comment by peat-psuwit** [comment]
`ubports-qa install PR_pulseaudio-modules-droid_15`

**Review by Flohack74 — APPROVED** [review]

**Comment by Flohack74** [comment]
Tested in SHIFT 6mq, Pixel 2XL and FP4. It doe snot work on the FP4 Halium 11 base...

**Comment by Flohack74** [comment]
I would still merge it to have a hotfix for users that need it.

**Review by fredldotme — APPROVED** [review]
With that explanation (Can't stop learning, kids!) and the code looking good, I think this can go in.

**Comment by amartinz** [comment]
Shouldn't this be sent to upstream as well?

**Comment by peat-psuwit** [comment]
> Shouldn't this be sent to upstream as well?

The SCO fake sink is our (actually Canonical's) custom code to handle holding HSP/HFP connection active during the call, so this isn't applicable upstream. I have no idea how upstream, SailfishOS (if not the same entity), or other distros handle this.

**Comment by amartinz** [comment]
> > Shouldn't this be sent to upstream as well?
> 
> The SCO fake sink is our (actually Canonical's) custom code to handle holding HSP/HFP connection active during the call, so this isn't applicable upstream. I have no idea how upstream, SailfishOS (if not the same entity), or other distros handle this.

My bad, i got lost in the branches again and did not see [we have introduced it ourselves](https://github.com/ubports/pulseaudio-modules-droid/commit/da32548db60d5f5ce09854959a6c5ed987250ffb).

Thank you for the thorough explanations!

**Comment by peat-psuwit** [comment]
For Halium 11 devices, see: https://github.com/ubports/pulseaudio-modules-droid-30/pull/2

**Pull request merged**
